In [53]:
import nltk
import re
import numpy as np
from nltk.corpus import stopwords

In [54]:
# for use it in function tokenize
def extraction (sentence):
    sent=re.sub("[^\w]+",' ', sentence).split()
    sent_clean=[w.lower() for w in sent if w not in stopwords.words("english")]
    return sent_clean

In [55]:
def tokenize (sentences):
    words =[]
    for sent in sentences:
        w= extraction(sent)
        words.extend(w)
    words=sorted(list(set(words)))   
    return words

In [56]:
# difference between append vs extend

# S1 = ['it','was','the','best','of']
# S2 = ['i','love','python','so','much']
# S3 = ['he','was','playing','the','game']
#w=[]
#w.append(S1)
#w.append(S2)
#w.append(S3)
# w= [['it','was','the','best','of'] , ['i','love','python','so','much'] , ['he','was','playing','the','game']]

#t=[]
#t.extend(S1)
#t.extend(S2)
#t.extend(S3)
# t = ['it','was','the','best','of','i','love','python','so','much','he','was','playing','the','game']


In [57]:
text = "Mary and Samantha arrived at the bus station early but waited until noon for the bus"

In [58]:
print(extraction(text))

['mary', 'samantha', 'arrived', 'bus', 'station', 'early', 'waited', 'noon', 'bus']


In [59]:
print(tokenize(extraction(text)))

['arrived', 'bus', 'early', 'mary', 'noon', 'samantha', 'station', 'waited']


In [73]:
sentences = ["Joe waited for the train",
                "The train was late",
                "Mary and Samantha took the bus",
               "I looked for Mary and Samantha at the bus station",
                "Mary and Samantha arrived at the bus station early but waited until noon for the bus"]


In [74]:
print(tokenize(sentences))

['arrived', 'bus', 'early', 'i', 'joe', 'late', 'looked', 'mary', 'noon', 'samantha', 'station', 'the', 'took', 'train', 'waited']


In [79]:
def BOW (sentences):
    vocab=tokenize(sentences)
    print (f"words :\n {vocab}\n\n")
    for sent in sentences:
        words=extraction(sent)
        bag=np.zeros(len(vocab))
        for w in words:
            for i,word in enumerate(vocab):
                if word==w:
                    bag[i]=+1
        print(f"{sent}\n{bag}\n------------------------------------------")            

In [80]:
BOW(sentences)

words :
 ['arrived', 'bus', 'early', 'i', 'joe', 'late', 'looked', 'mary', 'noon', 'samantha', 'station', 'the', 'took', 'train', 'waited']


Joe waited for the train
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1.]
------------------------------------------
The train was late
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 1. 0. 1. 0.]
------------------------------------------
Mary and Samantha took the bus
[0. 1. 0. 0. 0. 0. 0. 1. 0. 1. 0. 0. 1. 0. 0.]
------------------------------------------
I looked for Mary and Samantha at the bus station
[0. 1. 0. 1. 0. 0. 1. 1. 0. 1. 1. 0. 0. 0. 0.]
------------------------------------------
Mary and Samantha arrived at the bus station early but waited until noon for the bus
[1. 1. 1. 0. 0. 0. 0. 1. 1. 1. 1. 0. 0. 0. 1.]
------------------------------------------


In [91]:
#BOW by sklearn
from sklearn.feature_extraction.text import CountVectorizer
vectorizer=CountVectorizer()
sent=vectorizer.fit_transform(sentences)

for i in range(len(sentences)):
    print(sentences[i])
    # as array
    print("array : ",sent.toarray()[i])
    # as list
    print("list : ",list(sent.toarray()[i]))
    print("--------------------------------------------")

Joe waited for the train
array :  [0 0 0 0 0 0 1 1 0 0 0 0 0 0 1 0 1 0 1 0]
list :  [0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0]
--------------------------------------------
The train was late
array :  [0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 1 0 0 1]
list :  [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1]
--------------------------------------------
Mary and Samantha took the bus
array :  [1 0 0 1 0 0 0 0 0 0 1 0 1 0 1 1 0 0 0 0]
list :  [1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0]
--------------------------------------------
I looked for Mary and Samantha at the bus station
array :  [1 0 1 1 0 0 1 0 0 1 1 0 1 1 1 0 0 0 0 0]
list :  [1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0]
--------------------------------------------
Mary and Samantha arrived at the bus station early but waited until noon for the bus
array :  [1 1 1 2 1 1 1 0 0 0 1 1 1 1 2 0 0 1 1 0]
list :  [1, 1, 1, 2, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 2, 0, 0, 1, 1, 0]
----------

In [93]:
text = "ذهب محمد و شريف الي المدرسة هذا اليوم"

In [94]:
print(extraction(text))

['ذهب', 'محمد', 'و', 'شريف', 'الي', 'المدرسة', 'هذا', 'اليوم']


In [95]:
print(tokenize(extraction(text)))

['المدرسة', 'الي', 'اليوم', 'ذهب', 'شريف', 'محمد', 'هذا', 'و']


In [96]:
sentences = ["ذهب محمد الي الجامعة",
                "نجحت مني في الاختبار",
                "تمكن محمد من السفر هذا اليوم",
               "اعتقد ان جورج سيتصل بنا اليوم",
                "لا اظن ان الاختبار سيكون سهلا"]

In [97]:
BOW(sentences)

words :
 ['اظن', 'اعتقد', 'الاختبار', 'الجامعة', 'السفر', 'الي', 'اليوم', 'ان', 'بنا', 'تمكن', 'جورج', 'ذهب', 'سهلا', 'سيتصل', 'سيكون', 'في', 'لا', 'محمد', 'من', 'مني', 'نجحت', 'هذا']


ذهب محمد الي الجامعة
[0. 0. 0. 1. 0. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
------------------------------------------
نجحت مني في الاختبار
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 1. 1. 0.]
------------------------------------------
تمكن محمد من السفر هذا اليوم
[0. 0. 0. 0. 1. 0. 1. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 1. 1. 0. 0. 1.]
------------------------------------------
اعتقد ان جورج سيتصل بنا اليوم
[0. 1. 0. 0. 0. 0. 1. 1. 1. 0. 1. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
------------------------------------------
لا اظن ان الاختبار سيكون سهلا
[1. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 1. 0. 1. 0. 0. 0. 0. 0.]
------------------------------------------


In [98]:
#BOW by sklearn
from sklearn.feature_extraction.text import CountVectorizer
vectorizer=CountVectorizer()
sent=vectorizer.fit_transform(sentences)

for i in range(len(sentences)):
    print(sentences[i])
    # as array
    print("array : ",sent.toarray()[i])
    # as list
    print("list : ",list(sent.toarray()[i]))
    print("--------------------------------------------")

ذهب محمد الي الجامعة
array :  [0 0 0 1 0 1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0]
list :  [0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0]
--------------------------------------------
نجحت مني في الاختبار
array :  [0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 1 0]
list :  [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0]
--------------------------------------------
تمكن محمد من السفر هذا اليوم
array :  [0 0 0 0 1 0 1 0 0 1 0 0 0 0 0 0 0 1 1 0 0 1]
list :  [0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1]
--------------------------------------------
اعتقد ان جورج سيتصل بنا اليوم
array :  [0 1 0 0 0 0 1 1 1 0 1 0 0 1 0 0 0 0 0 0 0 0]
list :  [0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0]
--------------------------------------------
لا اظن ان الاختبار سيكون سهلا
array :  [1 0 1 0 0 0 0 1 0 0 0 0 1 0 1 0 1 0 0 0 0 0]
list :  [1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0]
---------------------------------------